path = '/home/ss_students/mtp/modality_pipeline_wft_v3-main/utils_custom/monai_losses.py'
with open(path, 'r') as f:
    content = f.read()

target = 'device = torch.device(" cuda)nperc_loss = MRIPerceptualLoss().to(device)nl1 = nn.L1Loss()nlambda_perc = 0.05\n\ndef loss_fn(pred, target):n return l1(pred, target) + lambda_perc Antigravity-server.tar.gz AppData Application Data Contacts Cookies Desktop Documents Documnents Downloads Favorites Links Local Settings Music My Documents NTUSER.DAT NTUSER.DAT{7670c108-d2a0-11ef-a9f0-010101010000}.TM.blf NTUSER.DAT{7670c108-d2a0-11ef-a9f0-010101010000}.TMContainer00000000000000000001.regtrans-ms NTUSER.DAT{7670c108-d2a0-11ef-a9f0-010101010000}.TMContainer00000000000000000002.regtrans-ms NetHood OneDrive Pictures PrintHood QSVD Recent Saved Games Searches SendTo Start Menu Templates Untitled.ipynb Untitled6 (1).ipynb Untitled6 (1).py Videos Y_test.pkl Y_train.pkl Y_val.pkl anaconda3 cache edb_npgsql.exe edb_pem_agent.exe edb_pgagent_pg17.exe edb_pgbouncer.exe edb_pgjdbc.exe edb_psqlodbc.exe edb_psqlodbc.exe-20250501193012 edb_sqlprofiler_pg17.exe gptoss_preds.json icd_top50_dataset.pkl label_binarizer.pkl llama_preds.json llm_direct_validation_comparison.csv neurodiversity-chatbot node_modules ntuser.dat.LOG1 ntuser.dat.LOG2 ntuser.ini ollama_llm_comparison_val.csv pemhttpd.exe postgis_3_5_pg17.exe postgresql_17.exe pytorch-transformer qsvd_project.tar.gz scikit_learn_data source test test_df.pkl three_role_validation_comparison.csv train_df.pkl val_df.pkl wekafiles perc_loss(pred, target)
replacement = if __name__ == \__main__\:\n device = torch.device(cuda)n perc_loss = MRIPerceptualLoss().to(device)n l1 = nn.L1Loss()n lambda_perc = 0.05\n\n def loss_fn(pred, target):n return l1(pred, target) + lambda_perc Antigravity-server.tar.gz AppData Application Data Contacts Cookies Desktop Documents Documnents Downloads Favorites Links Local Settings Music My Documents NTUSER.DAT NTUSER.DAT{7670c108-d2a0-11ef-a9f0-010101010000}.TM.blf NTUSER.DAT{7670c108-d2a0-11ef-a9f0-010101010000}.TMContainer00000000000000000001.regtrans-ms NTUSER.DAT{7670c108-d2a0-11ef-a9f0-010101010000}.TMContainer00000000000000000002.regtrans-ms NetHood OneDrive Pictures PrintHood QSVD Recent Saved Games Searches SendTo Start Menu Templates Untitled.ipynb Untitled6 (1).ipynb Untitled6 (1).py Videos Y_test.pkl Y_train.pkl Y_val.pkl anaconda3 cache edb_npgsql.exe edb_pem_agent.exe edb_pgagent_pg17.exe edb_pgbouncer.exe edb_pgjdbc.exe edb_psqlodbc.exe edb_psqlodbc.exe-20250501193012 edb_sqlprofiler_pg17.exe gptoss_preds.json icd_top50_dataset.pkl label_binarizer.pkl llama_preds.json llm_direct_validation_comparison.csv neurodiversity-chatbot node_modules ntuser.dat.LOG1 ntuser.dat.LOG2 ntuser.ini ollama_llm_comparison_val.csv pemhttpd.exe postgis_3_5_pg17.exe postgresql_17.exe pytorch-transformer qsvd_project.tar.gz scikit_learn_data source test test_df.pkl three_role_validation_comparison.csv train_df.pkl val_df.pkl wekafiles perc_loss(pred, target)

if target in content:
    content = content.replace(target, replacement)
    with open(path, w) as f:
        f.write(content)
    print(Successfully patched monai_losses.py)
else:
    print(Target string not found or already patched)
